version: '3'
services:

  ip2tor-host:
    build:
      context: .
      dockerfile: .docker/Dockerfile
      args:
        HOST_IP: ${IP2TOR_HOST_IP}
    container_name: ip2tor-host
    volumes:
      - .:/home/ip2tor
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    network_mode: "host"
  tos:
    build:
      context: .
      dockerfile: .docker/tos/tos.Dockerfile
    container_name: ip2tor-host-tos
    ports:
      - ${TOS_PORT}:${TOS_PORT}
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    networks:
      - hostnet
  cron:
    build:
      context: .
      dockerfile: .docker/cron/cron.Dockerfile
    container_name: ip2tor-host-cron
    volumes:
      - .:/home/ip2tor
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    networks:
      - hostnet
  nginx:
    image: nginx
    container_name: ip2tor-host-nginx
    hostname: nginx
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    ports:
      - ${NGINX_HTTP_PORT}:${NGINX_HTTP_PORT}
      - ${NGINX_HTTPS_PORT}:${NGINX_HTTPS_PORT}
    volumes:
      - .docker/nginx:/etc/nginx/templates
      - ./logs/nginx:/var/log/nginx
      - ./ssl/${NOSTR_DOMAIN}:/etc/nginx/ssl/${NOSTR_DOMAIN}
    environment:
      - HTTP_SERVER_PORT=${HTTP_SERVER_PORT}
      - NGINX_HTTP_PORT=${NGINX_HTTP_PORT}
      - NGINX_HTTPS_PORT=${NGINX_HTTPS_PORT}
      - NOSTR_DOMAIN=${NOSTR_DOMAIN}
      - NOSTR_SHOP_URL=${NOSTR_SHOP_URL}
    networks:
      - hostnet
networks:
  hostnet:
    driver: bridge